# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'statusUI_user.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_FeedbackStatusSelection(object):
    def setupUi(self, Dialog_FeedbackStatusSelection):
        Dialog_FeedbackStatusSelection.setObjectName("Dialog_FeedbackStatusSelection")
        Dialog_FeedbackStatusSelection.setWindowModality(QtCore.Qt.NonModal)
        Dialog_FeedbackStatusSelection.resize(745, 860)
        Dialog_FeedbackStatusSelection.setMinimumSize(QtCore.QSize(745, 860))
        Dialog_FeedbackStatusSelection.setMaximumSize(QtCore.QSize(860, 1000))
        self.groupBox = QtWidgets.QGroupBox(Dialog_FeedbackStatusSelection)
        self.groupBox.setGeometry(QtCore.QRect(10, 160, 721, 141))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.textEdit_Dlg_Sms = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_Dlg_Sms.setGeometry(QtCore.QRect(10, 40, 701, 91))
        self.textEdit_Dlg_Sms.setObjectName("textEdit_Dlg_Sms")
        self.layoutWidget = QtWidgets.QWidget(Dialog_FeedbackStatusSelection)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 90, 631, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_all = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.checkBox_all.setFont(font)
        self.checkBox_all.setObjectName("checkBox_all")
        self.horizontalLayout_3.addWidget(self.checkBox_all)
        self.checkBox_part = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.checkBox_part.setFont(font)
        self.checkBox_part.setObjectName("checkBox_part")
        self.horizontalLayout_3.addWidget(self.checkBox_part)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setMinimumSize(QtCore.QSize(82, 35))
        self.buttonBox.setMaximumSize(QtCore.QSize(820, 100))
        font = QtGui.QFont()
        font.setFamily("Adobe Myungjo Std M")
        font.setPointSize(12)
        self.buttonBox.setFont(font)
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_3.addWidget(self.buttonBox)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog_FeedbackStatusSelection)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 721, 51))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.Label.setFont(font)
        self.Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Label.setObjectName("Label")
        self.horizontalLayout_4.addWidget(self.Label)
        self.LineEdit_Dlg_Filename = QtWidgets.QLineEdit(self.layoutWidget1)
        self.LineEdit_Dlg_Filename.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.LineEdit_Dlg_Filename.setFont(font)
        self.LineEdit_Dlg_Filename.setReadOnly(True)
        self.LineEdit_Dlg_Filename.setObjectName("LineEdit_Dlg_Filename")
        self.horizontalLayout_4.addWidget(self.LineEdit_Dlg_Filename)
        self.widget = QtWidgets.QWidget(Dialog_FeedbackStatusSelection)
        self.widget.setGeometry(QtCore.QRect(13, 323, 711, 531))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.widget1 = QtWidgets.QWidget(self.groupBox_2)
        self.widget1.setGeometry(QtCore.QRect(10, 30, 281, 481))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_FindBank = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_FindBank.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.lineEdit_FindBank.setFont(font)
        self.lineEdit_FindBank.setObjectName("lineEdit_FindBank")
        self.verticalLayout.addWidget(self.lineEdit_FindBank)
        self.listView_BankList = QtWidgets.QListView(self.widget1)
        self.listView_BankList.setMinimumSize(QtCore.QSize(270, 400))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.listView_BankList.setFont(font)
        self.listView_BankList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView_BankList.setAlternatingRowColors(True)
        self.listView_BankList.setObjectName("listView_BankList")
        self.verticalLayout.addWidget(self.listView_BankList)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 30, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_FindBank = QtWidgets.QPushButton(self.widget)
        self.pushButton_FindBank.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_FindBank.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.pushButton_FindBank.setFont(font)
        self.pushButton_FindBank.setObjectName("pushButton_FindBank")
        self.verticalLayout_2.addWidget(self.pushButton_FindBank)
        self.pushButton_SelAll = QtWidgets.QPushButton(self.widget)
        self.pushButton_SelAll.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_SelAll.setFont(font)
        self.pushButton_SelAll.setObjectName("pushButton_SelAll")
        self.verticalLayout_2.addWidget(self.pushButton_SelAll)
        self.pushButton_SelOne = QtWidgets.QPushButton(self.widget)
        self.pushButton_SelOne.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.pushButton_SelOne.setFont(font)
        self.pushButton_SelOne.setObjectName("pushButton_SelOne")
        self.verticalLayout_2.addWidget(self.pushButton_SelOne)
        self.pushButton_DelOne = QtWidgets.QPushButton(self.widget)
        self.pushButton_DelOne.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.pushButton_DelOne.setFont(font)
        self.pushButton_DelOne.setObjectName("pushButton_DelOne")
        self.verticalLayout_2.addWidget(self.pushButton_DelOne)
        self.pushButton_DelAll = QtWidgets.QPushButton(self.widget)
        self.pushButton_DelAll.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.pushButton_DelAll.setFont(font)
        self.pushButton_DelAll.setObjectName("pushButton_DelAll")
        self.verticalLayout_2.addWidget(self.pushButton_DelAll)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.listView_BankList_Sel = QtWidgets.QListView(self.groupBox_3)
        self.listView_BankList_Sel.setGeometry(QtCore.QRect(9, 30, 281, 481))
        self.listView_BankList_Sel.setMinimumSize(QtCore.QSize(270, 400))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.listView_BankList_Sel.setFont(font)
        self.listView_BankList_Sel.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listView_BankList_Sel.setAlternatingRowColors(True)
        self.listView_BankList_Sel.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listView_BankList_Sel.setObjectName("listView_BankList_Sel")
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout.setStretch(0, 4)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 4)

        self.retranslateUi(Dialog_FeedbackStatusSelection)
        self.buttonBox.accepted.connect(Dialog_FeedbackStatusSelection.accept)
        self.buttonBox.rejected.connect(Dialog_FeedbackStatusSelection.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_FeedbackStatusSelection)

    def retranslateUi(self, Dialog_FeedbackStatusSelection):
        _translate = QtCore.QCoreApplication.translate
        Dialog_FeedbackStatusSelection.setWindowTitle(_translate("Dialog_FeedbackStatusSelection", "请选择反馈状态"))
        self.groupBox.setTitle(_translate("Dialog_FeedbackStatusSelection", "附加消息"))
        self.checkBox_all.setText(_translate("Dialog_FeedbackStatusSelection", "完全反馈"))
        self.checkBox_part.setText(_translate("Dialog_FeedbackStatusSelection", "部分反馈"))
        self.Label.setText(_translate("Dialog_FeedbackStatusSelection", "反馈文件"))
        self.groupBox_2.setTitle(_translate("Dialog_FeedbackStatusSelection", "查询银行列表"))
        self.pushButton_FindBank.setText(_translate("Dialog_FeedbackStatusSelection", "查   找"))
        self.pushButton_SelAll.setText(_translate("Dialog_FeedbackStatusSelection", ">>"))
        self.pushButton_SelOne.setText(_translate("Dialog_FeedbackStatusSelection", ">"))
        self.pushButton_DelOne.setText(_translate("Dialog_FeedbackStatusSelection", "<"))
        self.pushButton_DelAll.setText(_translate("Dialog_FeedbackStatusSelection", "<<"))
        self.groupBox_3.setTitle(_translate("Dialog_FeedbackStatusSelection", "反馈银行列表"))

