# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI_user.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(1024, 778)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 768))
        MainWindow.setMaximumSize(QtCore.QSize(14400, 9000))
        MainWindow.setSizeIncrement(QtCore.QSize(10, 7))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/main.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_ReceiveFile = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ReceiveFile.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ReceiveFile.sizePolicy().hasHeightForWidth())
        self.pushButton_ReceiveFile.setSizePolicy(sizePolicy)
        self.pushButton_ReceiveFile.setMinimumSize(QtCore.QSize(65, 65))
        self.pushButton_ReceiveFile.setMaximumSize(QtCore.QSize(65, 65))
        self.pushButton_ReceiveFile.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pic/receive.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ReceiveFile.setIcon(icon1)
        self.pushButton_ReceiveFile.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_ReceiveFile.setFlat(False)
        self.pushButton_ReceiveFile.setObjectName("pushButton_ReceiveFile")
        self.verticalLayout_4.addWidget(self.pushButton_ReceiveFile)
        self.ll1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ll1.sizePolicy().hasHeightForWidth())
        self.ll1.setSizePolicy(sizePolicy)
        self.ll1.setMinimumSize(QtCore.QSize(65, 18))
        self.ll1.setMaximumSize(QtCore.QSize(65, 18))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.ll1.setFont(font)
        self.ll1.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.ll1.setObjectName("ll1")
        self.verticalLayout_4.addWidget(self.ll1)
        self.pushButton_OpenFile = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_OpenFile.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_OpenFile.sizePolicy().hasHeightForWidth())
        self.pushButton_OpenFile.setSizePolicy(sizePolicy)
        self.pushButton_OpenFile.setMinimumSize(QtCore.QSize(65, 65))
        self.pushButton_OpenFile.setMaximumSize(QtCore.QSize(65, 65))
        self.pushButton_OpenFile.setLocale(QtCore.QLocale(QtCore.QLocale.Breton, QtCore.QLocale.France))
        self.pushButton_OpenFile.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/pic/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_OpenFile.setIcon(icon2)
        self.pushButton_OpenFile.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_OpenFile.setObjectName("pushButton_OpenFile")
        self.verticalLayout_4.addWidget(self.pushButton_OpenFile)
        self.ll2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ll2.sizePolicy().hasHeightForWidth())
        self.ll2.setSizePolicy(sizePolicy)
        self.ll2.setMinimumSize(QtCore.QSize(65, 18))
        self.ll2.setMaximumSize(QtCore.QSize(65, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ll2.setFont(font)
        self.ll2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.ll2.setObjectName("ll2")
        self.verticalLayout_4.addWidget(self.ll2)
        self.pushButton_AddFeedback = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_AddFeedback.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_AddFeedback.sizePolicy().hasHeightForWidth())
        self.pushButton_AddFeedback.setSizePolicy(sizePolicy)
        self.pushButton_AddFeedback.setMinimumSize(QtCore.QSize(65, 65))
        self.pushButton_AddFeedback.setMaximumSize(QtCore.QSize(65, 65))
        self.pushButton_AddFeedback.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/pic/link.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_AddFeedback.setIcon(icon3)
        self.pushButton_AddFeedback.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_AddFeedback.setObjectName("pushButton_AddFeedback")
        self.verticalLayout_4.addWidget(self.pushButton_AddFeedback)
        self.ll3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ll3.sizePolicy().hasHeightForWidth())
        self.ll3.setSizePolicy(sizePolicy)
        self.ll3.setMinimumSize(QtCore.QSize(65, 18))
        self.ll3.setMaximumSize(QtCore.QSize(65, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ll3.setFont(font)
        self.ll3.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.ll3.setObjectName("ll3")
        self.verticalLayout_4.addWidget(self.ll3)
        self.pushButton_AddFeedback_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_AddFeedback_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_AddFeedback_2.sizePolicy().hasHeightForWidth())
        self.pushButton_AddFeedback_2.setSizePolicy(sizePolicy)
        self.pushButton_AddFeedback_2.setMinimumSize(QtCore.QSize(65, 65))
        self.pushButton_AddFeedback_2.setMaximumSize(QtCore.QSize(65, 65))
        self.pushButton_AddFeedback_2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/pic/addmore.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_AddFeedback_2.setIcon(icon4)
        self.pushButton_AddFeedback_2.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_AddFeedback_2.setObjectName("pushButton_AddFeedback_2")
        self.verticalLayout_4.addWidget(self.pushButton_AddFeedback_2)
        self.ll4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ll4.sizePolicy().hasHeightForWidth())
        self.ll4.setSizePolicy(sizePolicy)
        self.ll4.setMinimumSize(QtCore.QSize(65, 18))
        self.ll4.setMaximumSize(QtCore.QSize(65, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ll4.setFont(font)
        self.ll4.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.ll4.setObjectName("ll4")
        self.verticalLayout_4.addWidget(self.ll4)
        self.pushButton_SendFile = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_SendFile.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_SendFile.sizePolicy().hasHeightForWidth())
        self.pushButton_SendFile.setSizePolicy(sizePolicy)
        self.pushButton_SendFile.setMinimumSize(QtCore.QSize(65, 65))
        self.pushButton_SendFile.setMaximumSize(QtCore.QSize(65, 65))
        self.pushButton_SendFile.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/pic/send.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_SendFile.setIcon(icon5)
        self.pushButton_SendFile.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_SendFile.setObjectName("pushButton_SendFile")
        self.verticalLayout_4.addWidget(self.pushButton_SendFile)
        self.ll5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ll5.sizePolicy().hasHeightForWidth())
        self.ll5.setSizePolicy(sizePolicy)
        self.ll5.setMinimumSize(QtCore.QSize(65, 18))
        self.ll5.setMaximumSize(QtCore.QSize(65, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ll5.setFont(font)
        self.ll5.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.ll5.setObjectName("ll5")
        self.verticalLayout_4.addWidget(self.ll5)
        self.pushButton_Modify = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Modify.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Modify.sizePolicy().hasHeightForWidth())
        self.pushButton_Modify.setSizePolicy(sizePolicy)
        self.pushButton_Modify.setMinimumSize(QtCore.QSize(65, 65))
        self.pushButton_Modify.setMaximumSize(QtCore.QSize(65, 65))
        self.pushButton_Modify.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/pic/modify.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Modify.setIcon(icon6)
        self.pushButton_Modify.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_Modify.setObjectName("pushButton_Modify")
        self.verticalLayout_4.addWidget(self.pushButton_Modify)
        self.ll6 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ll6.sizePolicy().hasHeightForWidth())
        self.ll6.setSizePolicy(sizePolicy)
        self.ll6.setMinimumSize(QtCore.QSize(65, 18))
        self.ll6.setMaximumSize(QtCore.QSize(65, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ll6.setFont(font)
        self.ll6.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.ll6.setObjectName("ll6")
        self.verticalLayout_4.addWidget(self.ll6)
        self.pushButton_Search = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Search.setMinimumSize(QtCore.QSize(65, 65))
        self.pushButton_Search.setMaximumSize(QtCore.QSize(65, 65))
        self.pushButton_Search.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/pic/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Search.setIcon(icon7)
        self.pushButton_Search.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_Search.setObjectName("pushButton_Search")
        self.verticalLayout_4.addWidget(self.pushButton_Search)
        self.ll7 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ll7.sizePolicy().hasHeightForWidth())
        self.ll7.setSizePolicy(sizePolicy)
        self.ll7.setMinimumSize(QtCore.QSize(65, 18))
        self.ll7.setMaximumSize(QtCore.QSize(65, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ll7.setFont(font)
        self.ll7.setAlignment(QtCore.Qt.AlignCenter)
        self.ll7.setObjectName("ll7")
        self.verticalLayout_4.addWidget(self.ll7)
        self.pushButton_Wechat = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Wechat.setMinimumSize(QtCore.QSize(65, 65))
        self.pushButton_Wechat.setMaximumSize(QtCore.QSize(65, 65))
        self.pushButton_Wechat.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/pic/wechat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Wechat.setIcon(icon8)
        self.pushButton_Wechat.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_Wechat.setObjectName("pushButton_Wechat")
        self.verticalLayout_4.addWidget(self.pushButton_Wechat)
        spacerItem = QtWidgets.QSpacerItem(59, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 2, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 1, 2, 2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(3, -1, 3, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.l1 = QtWidgets.QLabel(self.centralwidget)
        self.l1.setMinimumSize(QtCore.QSize(68, 0))
        self.l1.setMaximumSize(QtCore.QSize(68, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l1.setFont(font)
        self.l1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.l1.setAlignment(QtCore.Qt.AlignCenter)
        self.l1.setObjectName("l1")
        self.horizontalLayout_3.addWidget(self.l1)
        self.lineEdit_AskFileName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_AskFileName.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_AskFileName.setSizeIncrement(QtCore.QSize(2, 0))
        self.lineEdit_AskFileName.setAcceptDrops(False)
        self.lineEdit_AskFileName.setReadOnly(True)
        self.lineEdit_AskFileName.setObjectName("lineEdit_AskFileName")
        self.horizontalLayout_3.addWidget(self.lineEdit_AskFileName)
        self.l2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l2.sizePolicy().hasHeightForWidth())
        self.l2.setSizePolicy(sizePolicy)
        self.l2.setMinimumSize(QtCore.QSize(68, 0))
        self.l2.setMaximumSize(QtCore.QSize(68, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l2.setFont(font)
        self.l2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.l2.setAlignment(QtCore.Qt.AlignCenter)
        self.l2.setObjectName("l2")
        self.horizontalLayout_3.addWidget(self.l2)
        self.lineEdit_AskTime = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_AskTime.setEnabled(True)
        self.lineEdit_AskTime.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_AskTime.setAcceptDrops(False)
        self.lineEdit_AskTime.setReadOnly(True)
        self.lineEdit_AskTime.setObjectName("lineEdit_AskTime")
        self.horizontalLayout_3.addWidget(self.lineEdit_AskTime)
        self.l3 = QtWidgets.QLabel(self.centralwidget)
        self.l3.setMinimumSize(QtCore.QSize(68, 0))
        self.l3.setMaximumSize(QtCore.QSize(68, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l3.setFont(font)
        self.l3.setAlignment(QtCore.Qt.AlignCenter)
        self.l3.setObjectName("l3")
        self.horizontalLayout_3.addWidget(self.l3)
        self.LineEdit_User = QtWidgets.QLineEdit(self.centralwidget)
        self.LineEdit_User.setMinimumSize(QtCore.QSize(0, 0))
        self.LineEdit_User.setMaximumSize(QtCore.QSize(300, 16777215))
        self.LineEdit_User.setAcceptDrops(False)
        self.LineEdit_User.setReadOnly(True)
        self.LineEdit_User.setObjectName("LineEdit_User")
        self.horizontalLayout_3.addWidget(self.LineEdit_User)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.l4 = QtWidgets.QLabel(self.centralwidget)
        self.l4.setMinimumSize(QtCore.QSize(68, 0))
        self.l4.setMaximumSize(QtCore.QSize(68, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l4.setFont(font)
        self.l4.setAlignment(QtCore.Qt.AlignCenter)
        self.l4.setObjectName("l4")
        self.horizontalLayout_4.addWidget(self.l4)
        self.LineEdit_FeedbackID = QtWidgets.QLineEdit(self.centralwidget)
        self.LineEdit_FeedbackID.setMinimumSize(QtCore.QSize(0, 0))
        self.LineEdit_FeedbackID.setAcceptDrops(True)
        self.LineEdit_FeedbackID.setReadOnly(True)
        self.LineEdit_FeedbackID.setObjectName("LineEdit_FeedbackID")
        self.horizontalLayout_4.addWidget(self.LineEdit_FeedbackID)
        self.l5 = QtWidgets.QLabel(self.centralwidget)
        self.l5.setMinimumSize(QtCore.QSize(68, 0))
        self.l5.setMaximumSize(QtCore.QSize(68, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l5.setFont(font)
        self.l5.setAlignment(QtCore.Qt.AlignCenter)
        self.l5.setObjectName("l5")
        self.horizontalLayout_4.addWidget(self.l5)
        self.LineEdit_FeedbackTime = QtWidgets.QLineEdit(self.centralwidget)
        self.LineEdit_FeedbackTime.setMinimumSize(QtCore.QSize(0, 0))
        self.LineEdit_FeedbackTime.setAcceptDrops(False)
        self.LineEdit_FeedbackTime.setReadOnly(True)
        self.LineEdit_FeedbackTime.setObjectName("LineEdit_FeedbackTime")
        self.horizontalLayout_4.addWidget(self.LineEdit_FeedbackTime)
        self.l6 = QtWidgets.QLabel(self.centralwidget)
        self.l6.setMinimumSize(QtCore.QSize(68, 0))
        self.l6.setMaximumSize(QtCore.QSize(68, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l6.setFont(font)
        self.l6.setAlignment(QtCore.Qt.AlignCenter)
        self.l6.setObjectName("l6")
        self.horizontalLayout_4.addWidget(self.l6)
        self.LineEdit_FeedbackStatus = QtWidgets.QLineEdit(self.centralwidget)
        self.LineEdit_FeedbackStatus.setMinimumSize(QtCore.QSize(0, 0))
        self.LineEdit_FeedbackStatus.setMaximumSize(QtCore.QSize(300, 16777215))
        self.LineEdit_FeedbackStatus.setReadOnly(True)
        self.LineEdit_FeedbackStatus.setObjectName("LineEdit_FeedbackStatus")
        self.horizontalLayout_4.addWidget(self.LineEdit_FeedbackStatus)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.l7 = QtWidgets.QLabel(self.centralwidget)
        self.l7.setMinimumSize(QtCore.QSize(68, 0))
        self.l7.setMaximumSize(QtCore.QSize(68, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.l7.setFont(font)
        self.l7.setAlignment(QtCore.Qt.AlignCenter)
        self.l7.setObjectName("l7")
        self.horizontalLayout_2.addWidget(self.l7)
        self.LineEdit_FeedbackFile = QtWidgets.QLineEdit(self.centralwidget)
        self.LineEdit_FeedbackFile.setMinimumSize(QtCore.QSize(0, 0))
        self.LineEdit_FeedbackFile.setAcceptDrops(False)
        self.LineEdit_FeedbackFile.setReadOnly(True)
        self.LineEdit_FeedbackFile.setObjectName("LineEdit_FeedbackFile")
        self.horizontalLayout_2.addWidget(self.LineEdit_FeedbackFile)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(68, 0))
        self.label.setMaximumSize(QtCore.QSize(68, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.textBrowser_BankInfo = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_BankInfo.setObjectName("textBrowser_BankInfo")
        self.horizontalLayout.addWidget(self.textBrowser_BankInfo)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableView_Data = QtWidgets.QTableView(self.centralwidget)
        self.tableView_Data.setObjectName("tableView_Data")
        self.verticalLayout.addWidget(self.tableView_Data)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 6)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.textBrowser_Info = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_Info.setStyleSheet("font-size:15px; background:#696969")
        self.textBrowser_Info.setMinimumSize(QtCore.QSize(0, 100))
        self.textBrowser_Info.setMaximumSize(QtCore.QSize(16777215, 450))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.textBrowser_Info.setFont(font)
        self.textBrowser_Info.setObjectName("textBrowser_Info")
        self.verticalLayout_3.addWidget(self.textBrowser_Info)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionedit = QtWidgets.QAction(MainWindow)
        self.actionedit.setObjectName("actionedit")
        self.actionfile_open = QtWidgets.QAction(MainWindow)
        self.actionfile_open.setObjectName("actionfile_open")
        self.actionFind = QtWidgets.QAction(MainWindow)
        self.actionFind.setObjectName("actionFind")

        # 》》》》》》》》》》》》》》》》》》》》》》》》
        self.Tip_Btn_Rec = QtWidgets.QLineEdit(self.centralwidget)
        self.Tip_Btn_Rec.setEnabled(True)
        self.Tip_Btn_Rec.setAcceptDrops(False)
        self.Tip_Btn_Rec.setReadOnly(True)
        self.Tip_Btn_Rec.setObjectName("self.lineEdit_Tip_new")
        self.Tip_Btn_Rec.setAlignment(Qt.AlignCenter | Qt.AlignVCenter)
        self.Tip_Btn_Rec.setStyleSheet("color:#ffffff;font-size:16px; border-radius:10px; background:#FF4500;"
                                       "border-width:0; border-style:outset")
        self.Tip_Btn_Rec.setVisible(False)

        self.Tip_Btn_Add = QtWidgets.QLineEdit(self.centralwidget)
        self.Tip_Btn_Add.setEnabled(True)
        self.Tip_Btn_Add.setAcceptDrops(False)
        self.Tip_Btn_Add.setReadOnly(True)
        self.Tip_Btn_Add.setObjectName("self.lineEdit_Tip_new")
        self.Tip_Btn_Add.setAlignment(Qt.AlignCenter | Qt.AlignVCenter)
        self.Tip_Btn_Add.setStyleSheet("color:#ffffff;font-size:16px; border-radius:10px; background:#FF4500;"
                                       "border-width:0; border-style:outset")
        self.Tip_Btn_Add.setVisible(False)

        self.Tip_Btn_Addmore = QtWidgets.QLineEdit(self.centralwidget)
        self.Tip_Btn_Addmore.setEnabled(True)
        self.Tip_Btn_Addmore.setAcceptDrops(False)
        self.Tip_Btn_Addmore.setReadOnly(True)
        self.Tip_Btn_Addmore.setObjectName("self.lineEdit_Tip_new")
        self.Tip_Btn_Addmore.setAlignment(Qt.AlignCenter | Qt.AlignVCenter)
        self.Tip_Btn_Addmore.setStyleSheet("color:#ffffff;font-size:16px; border-radius:10px; background:#FF4500;"
                                           "border-width:0; border-style:outset")
        self.Tip_Btn_Addmore.setVisible(False)

        self.Tip_Btn_Send = QtWidgets.QLineEdit(self.centralwidget)
        self.Tip_Btn_Send.setEnabled(True)
        self.Tip_Btn_Send.setAcceptDrops(False)
        self.Tip_Btn_Send.setReadOnly(True)
        self.Tip_Btn_Send.setObjectName("self.lineEdit_Tip_new")
        self.Tip_Btn_Send.setAlignment(Qt.AlignCenter | Qt.AlignVCenter)
        self.Tip_Btn_Send.setStyleSheet("color:#ffffff;font-size:16px; border-radius:10px; background:#FF4500;"
                                        "border-width:0; border-style:outset")
        self.Tip_Btn_Send.setVisible(False)
        # 》》》》》》》》》》》》》》》》》》》》》》》》
        self.Frame = QtWidgets.QWidget(MainWindow)
        self.Frame.setStyleSheet("background:#F0F0F0")
        self.Frame.setObjectName("Frame")
        self.Frame.resize(975, 38)
        self.Frame.setMinimumSize(QtCore.QSize(900, 38))
        self.Frame.setMaximumSize(QtCore.QSize(19600, 38))
        #   self.Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        #  self.Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 661, 38))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(6, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label")
        self.horizontalLayout.addWidget(self.label_10)
        self.comboBox_area = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_area.setStyleSheet("border-style:solid;border-width:1px")
        # self.comboBox_area.setStyleSheet("QComboBox::drop-down{border-width:1px}")
        self.comboBox_area.setMinimumSize(QtCore.QSize(130, 25))
        self.comboBox_area.setMaximumSize(QtCore.QSize(130, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.comboBox_area.setFont(font)
        self.comboBox_area.setObjectName("comboBox_area")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.comboBox_area.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_area)
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.lineEdit_keyword = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_keyword.setMinimumSize(QtCore.QSize(200, 25))
        self.lineEdit_keyword.setMaximumSize(QtCore.QSize(200, 25))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.lineEdit_keyword.setFont(font)
        self.lineEdit_keyword.setObjectName("lineEdit_keyword")
        self.horizontalLayout.addWidget(self.lineEdit_keyword)

        self.pushButton_Backward = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_Backward.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_Backward.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_Backward.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/back.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.pushButton_Backward.setIcon(icon)
        self.pushButton_Backward.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_Backward.setFlat(True)
        self.pushButton_Backward.setObjectName("pushButton_Backward")
        self.horizontalLayout.addWidget(self.pushButton_Backward)

        self.pushButton_Find = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_Find.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_Find.setSizeIncrement(QtCore.QSize(35, 35))
        self.pushButton_Find.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pic/search2.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.pushButton_Find.setIcon(icon1)
        self.pushButton_Find.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_Find.setFlat(True)
        self.pushButton_Find.setObjectName("pushButton_Find")
        self.horizontalLayout.addWidget(self.pushButton_Find)

        self.pushButton_Forward = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_Forward.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_Forward.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_Forward.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/pic/next.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.pushButton_Forward.setIcon(icon2)
        self.pushButton_Forward.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_Forward.setFlat(True)
        self.pushButton_Forward.setObjectName("pushButton_Forward")
        self.horizontalLayout.addWidget(self.pushButton_Forward)

        spacerItem1 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.Frame.hide()
        # 》》》》》》》》》》》》》》》》》》》》》》》》

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "协查文件传输系统（协作单位）"))
        self.pushButton_ReceiveFile.setToolTip(_translate("MainWindow", "接收查询"))
        self.ll1.setText(_translate("MainWindow", "接收查询"))
        self.ll2.setText(_translate("MainWindow", "打开查询"))
        self.ll3.setText(_translate("MainWindow", "添加反馈"))
        self.ll4.setText(_translate("MainWindow", "补充反馈"))
        self.ll5.setText(_translate("MainWindow", "发送反馈"))
        self.ll6.setText(_translate("MainWindow", "修改反馈"))
        self.ll7.setText(_translate("MainWindow", "查询记录"))
        self.l1.setText(_translate("MainWindow", "查询编号"))
        self.l2.setText(_translate("MainWindow", "查询时间"))
        self.l3.setText(_translate("MainWindow", "申请单位"))
        self.l4.setText(_translate("MainWindow", "反馈编号"))
        self.l5.setText(_translate("MainWindow", "反馈时间"))
        self.l6.setText(_translate("MainWindow", "反馈状态"))
        self.l7.setText(_translate("MainWindow", "反馈文件"))
        self.label.setText(_translate("MainWindow", "附加信息"))
        self.actionedit.setText(_translate("MainWindow", "Open File"))
        self.actionfile_open.setText(_translate("MainWindow", "Open file..."))
        self.actionFind.setText(_translate("MainWindow", "Find..."))
        self.label_10.setText(_translate("Frame", "查询范围"))
        self.comboBox_area.setItemText(0, _translate("Frame", "查询时间"))
        self.comboBox_area.setItemText(1, _translate("Frame", "申请单位"))
        self.comboBox_area.setItemText(2, _translate("Frame", "查询时间"))
        self.comboBox_area.setItemText(3, _translate("Frame", "对象名称"))
        self.comboBox_area.setItemText(4, _translate("Frame", "查询编号"))
        self.comboBox_area.setItemText(5, _translate("Frame", "反馈时间"))
        self.comboBox_area.setItemText(6, _translate("Frame", "反馈文件名称"))
        self.comboBox_area.setItemText(7, _translate("Frame", "反馈编号"))

        self.label_11.setText(_translate("Frame", "关键字"))
import OT_rc
