# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginUI_user.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import json
class Ui_Dialog_Login(object):
    def setupUi(self, Dialog_Login):
        Dialog_Login.setObjectName("Dialog_Login")
        Dialog_Login.setWindowModality(QtCore.Qt.WindowModal)
        Dialog_Login.resize(462, 696)
        Dialog_Login.setMinimumSize(QtCore.QSize(462, 696))
        Dialog_Login.setMaximumSize(QtCore.QSize(462, 696))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/main.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog_Login.setWindowIcon(icon)
        Dialog_Login.setLayoutDirection(QtCore.Qt.LeftToRight)
        Dialog_Login.setAutoFillBackground(True)
        Dialog_Login.setStyleSheet("")
        Dialog_Login.setModal(True)
        self.pushButton_Login = QtWidgets.QPushButton(Dialog_Login)
        self.pushButton_Login.setGeometry(QtCore.QRect(170, 580, 121, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.pushButton_Login.setFont(font)
        self.pushButton_Login.setObjectName("pushButton_Login")
        self.listWidget = QtWidgets.QListWidget(Dialog_Login)
        self.listWidget.setGeometry(QtCore.QRect(-670, 180, 256, 192))
        self.listWidget.setObjectName("listWidget")
        self.checkBox = QtWidgets.QCheckBox(Dialog_Login)
        self.checkBox.setGeometry(QtCore.QRect(180, 510, 120, 50))
        self.checkBox.setMinimumSize(QtCore.QSize(120, 50))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(11)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.layoutWidget = QtWidgets.QWidget(Dialog_Login)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 320, 271, 167))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.gridLayout.setObjectName("gridLayout")
        self.Label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.Label.setFont(font)
        self.Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Label.setObjectName("Label")
        self.gridLayout.addWidget(self.Label, 0, 0, 1, 1)
        self.comboBox_Name = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_Name.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.comboBox_Name.setFont(font)
        self.comboBox_Name.setEditable(True)
        self.comboBox_Name.setObjectName("comboBox_Name")
        self.gridLayout.addWidget(self.comboBox_Name, 0, 1, 1, 1)
        self.Label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.Label_2.setFont(font)
        self.Label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_2.setObjectName("Label_2")
        self.gridLayout.addWidget(self.Label_2, 1, 0, 1, 1)
        self.LineEdit_Password = QtWidgets.QLineEdit(self.layoutWidget)
        self.LineEdit_Password.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.LineEdit_Password.setFont(font)
        self.LineEdit_Password.setObjectName("LineEdit_Password")
        self.gridLayout.addWidget(self.LineEdit_Password, 1, 1, 1, 1)
        self.Label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.Label_3.setFont(font)
        self.Label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_3.setObjectName("Label_3")
        self.gridLayout.addWidget(self.Label_3, 2, 0, 1, 1)
        self.LineEdit_ServerIP = QtWidgets.QLineEdit(self.layoutWidget)
        self.LineEdit_ServerIP.setMinimumSize(QtCore.QSize(0, 35))
        self.LineEdit_ServerIP.setObjectName("LineEdit_ServerIP")
        self.gridLayout.addWidget(self.LineEdit_ServerIP, 2, 1, 1, 1)
        self.Label_ServerPort = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.Label_ServerPort.setFont(font)
        self.Label_ServerPort.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_ServerPort.setObjectName("Label_ServerPort")
        self.gridLayout.addWidget(self.Label_ServerPort, 3, 0, 1, 1)
        self.LineEdit_ServerPort = QtWidgets.QLineEdit(self.layoutWidget)
        self.LineEdit_ServerPort.setMinimumSize(QtCore.QSize(0, 35))
        self.LineEdit_ServerPort.setObjectName("LineEdit_ServerPort")
        self.gridLayout.addWidget(self.LineEdit_ServerPort, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(Dialog_Login)
        self.label.setGeometry(QtCore.QRect(-6, 0, 471, 696))
        self.label.setMinimumSize(QtCore.QSize(465, 696))
        self.label.setMaximumSize(QtCore.QSize(490, 696))
        self.label.setStyleSheet("background-image: url(:/pic/login.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.raise_()
        self.pushButton_Login.raise_()
        self.listWidget.raise_()
        self.checkBox.raise_()
        self.layoutWidget.raise_()

        self.retranslateUi(Dialog_Login)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Login)

    def retranslateUi(self, Dialog_Login):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Login.setWindowTitle(_translate("Dialog_Login", "欢迎"))
        self.pushButton_Login.setText(_translate("Dialog_Login", "登  录"))
        self.checkBox.setText(_translate("Dialog_Login", "记住密码"))
        self.Label.setText(_translate("Dialog_Login", "用      户"))
        self.Label_2.setText(_translate("Dialog_Login", "密      码"))
        self.Label_3.setText(_translate("Dialog_Login", "服务器地址"))
        self.Label_ServerPort.setText(_translate("Dialog_Login", "服务器端口"))
        with open('userInfoSet.json', 'r', encoding='UTF-8') as f:
                data = json.load(f)
                f.close()
        i = 0
        # print(data["client"])
        for key, value in data["client"].items():
            self.comboBox_Name.addItem("")
            self.comboBox_Name.setItemText(i, _translate("Dialog_ChangeFileName", key))
            i = i + 1
import OT_rc
